From bac265c482cc9226ce1ad7bc67c07fa1e96b0571 Mon Sep 17 00:00:00 2001
From: Florent Viard <fviard@lacie.com>
Date: Thu, 1 Oct 2015 00:44:36 +0200
Subject: [PATCH] Fixes #636. Also remove the temporary file when encountering
 an S3Error.

---
 s3cmd | 9 ++++++++-
 1 file changed, 8 insertions(+), 1 deletion(-)

diff --git a/s3cmd b/s3cmd
index 195a2a7..e7b5cc4 100755
--- a/s3cmd
+++ b/s3cmd
@@ -1204,7 +1204,10 @@ def cmd_sync_remote2local(args):
                 error(u"Download of '%s' failed too many times (Last Reason: %s). "
                       "This is usually a transient error, please try again "
                       "later." % (file, exc))
-                os.unlink(deunicodise(chkptfname))
+                try:
+                    os.unlink(deunicodise(chkptfname))
+                except Exception, sub_exc:
+                    warning(u"Error deleting temporary file %s (Reason: %s)", (chkptfname, sub_exc))
                 if cfg.stop_on_error:
                     ret = EX_DATAERR
                     error(u"Exiting now because of --stop-on-error")
@@ -1213,6 +1216,10 @@ def cmd_sync_remote2local(args):
                 continue
             except S3Error, exc:
                 warning(u"Remote file '%s'. S3Error: %s" % (exc.resource, exc))
+                try:
+                    os.unlink(deunicodise(chkptfname))
+                except Exception, sub_exc:
+                    warning(u"Error deleting temporary file %s (Reason: %s)", (chkptfname, sub_exc))
                 if cfg.stop_on_error:
                     raise
                 ret = EX_PARTIAL
